name: deploy

on:
    push:
        branches:
            - main
            - feature/* # for feature branches
            - bugfix/* # for bugfix branches
        paths-ignore:
            - .github/workflows/deploy.yml # ignore changes to this file
            - README.md # ignore changes to this file   
    workflow_dispatch: # allow manual trigger of the workflow         

jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20 # Use Node.js version 20.x

            - name: Print Node.js version
              run: node -v 

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm run test
    
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20 # Use Node.js version 20.x

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build  

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build-artifacts
                  path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v3
              with:
                  name: build-artifacts
                  path: dist
        
            - name: Deploy to production server
              env:
                  DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
                  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
                  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
              run: |
                  echo "Deploying to production server..."
                  ssh -i "$DEPLOY_KEY" "$DEPLOY_USER@$DEPLOY_SERVER" "mkdir -p /var/www/app && rm -rf /var/www/app/*"
                  scp -i "$DEPLOY_KEY" -r dist/* "$DEPLOY_USER@$DEPLOY_SERVER:/var/www/app/"
                  ssh -i "$DEPLOY_KEY" "$DEPLOY_USER@$DEPLOY_SERVER" "sudo systemctl restart app"