name: deploy
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: code checkout
              uses: actions/checkout@v2
            - name: node version cheekout
              uses: actions/setup-node@v2
              with:
                  node-version: 20 # use the latest version of nodejs 20.x
            - name: print node version
              run: node -v 

            - name: install dependencies
              run: npm ci

            - name: run tests
              run: npm run test

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: code checkout
              uses: actions/checkout@v2
            - name: node version cheekout
              uses: actions/setup-node@v2
              with:
                  node-version: 20 # use the latest version of nodejs 20.x

            - name: install dependencies
              run: npm ci

            - name: deploy to production server
              run: echo "Deploying to production server..."          
